### PR TITLE
Add Simplified Chinese translation

### PR DESCRIPTION
**Pull request by dyxxzgc**
- Simplified Chinese labeled as `zh-Hans`. If future contributers want to add Traditional Chinese translation then it will be `zh-Hant`.

- This translation mostly used Chinese punctuation marks like `，` `。` `！` `：` `“”` `——`. I deleted most spaces after the marks when I translate, since Chinese punctuation marks leave enough space between characters.

Such changes could be seen in the following sample sentence.
> [b]Cataclysm: Dark Days Ahead[/b] is a turn-based survival game set in a post-apocalyptic world. Scavenge, explore, craft, build, farm, repair and modify vehicles, install bionics, mutate, defend against [color=#009900]zombies[/color] and countless other monstrosities — all in a limitless, procedurally generated world!

translated to

> [b]Cataclysm: Dark Days Ahead[/b] 是一款以世界末日为背景的回合制生存游戏。搜刮，探索，制造，建造，耕种，修理并改装载具，安装生化插件，变异，抵御[color=#009900]僵尸[/color]和无数其他怪物的攻击——一切尽在一个无限的，程序生成的世界中！

- when I `git add text/text.csv` it popped `warning: LF will be replaced by CRLF in text/text.csv.
The file will have its original line endings in your working directory`. I don't know if it was OK but anyway I continued.

### CODE REVIEW

**Comment by qrrk** [comment]
I ran into a problem when importing the translation into the project: turns out, Godot makes no distinction between Simplified and Traditional Chinese, and only supports locales zh, zh_CN, zh_HK, zh_SG and zh_TW.

I was getting import errors, so I decided to rename your translation to just "zh". The locale name does not show up anywhere for the end user anyway, and the language list has the correct name: 简体字.

Not sure how we will handle addition of Traditional Chinese if someone decides to do it in the future, but let's think about that when it comes up. Right now we have a different problem: the font I use for launcher UI, OpenSans, does not have the necessary characters in it:

image

Can you think of any font with a sufficiently permissive license that we could use?

**Comment by dyxxzgc** [comment]
> I was getting import errors, so I decided to rename your translation to just "zh". The locale name does not show up anywhere for the end user anyway, and I added the correct name into the language list: 简体字.

Typically we use zh_CN to represent 简体字/简体中文, and zh_TW to represent 繁體字/繁體中文, in this case.

About the font, [Source Han Sans](https://github.com/adobe-fonts/source-han-sans) would be fine.

**Comment by qrrk** [comment]
> Typically we use zh_CN to represent 简体字/简体中文, and zh_TW to represent 繁體字/繁體中文, in this case.\

It's just that with English and Russian I used only the language name, without the country. I think we should maintain that pattern for now. This way, for users whose system locale is any of `zh_*`, it will default to your translation. In the future, we can change things around to use `zh_CN` and `zh_TW`, if needed.

> About the font, Source Han Sans would be fine.

Thanks. I already considered it, but was misled by Adobe Fonts FAQ into thinking that embedding in applications was forbidden. The license in GitHub repository clearly indicates that is isn't. I think it will work.

**Comment by qrrk** [comment]
Alright, I've added the font as a fallback, seems to be working fine.

Screenshot_20220309_144255

I can't verify on my own that your translation is accurate and bug-free, so I suggest you do it before we merge this. Run the project in Godot and play around with it. Check all the tabs, dialogs and tooltips. Make sure all translation pieces show up and that they suit the context in which they are used. Make corrections and commit them, if needed.

If you can't run the project in Godot, let me know, and I can build it for you (for Windows or Linux).

**Comment by dyxxzgc** [comment]
Checked!

**Pull request merged**
