### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by JuaniElias**
I translated all files to Spanish (`es`) and configured some of the Godot files but wasn't able to start the project and properly test them to see how they look.
It's likely that some buttons will be too large due to some longer strings. So please test it and let me know what changes should I make.

### CODE REVIEW

**Comment by qrrk** [comment]
Thank you for your work! I've added your translation to the language drop-down, so if you pull my changes and run the project in Godot, you should now be able to select it without editing the config file.

Looks like you've missed most setting names, as well as all of their tooltips:

image

Also, as you suspected, the Set Font buttons end up too wide:

image

This has been a problem with almost every translation that I didn't do myself. I've been thinking about arranging those buttons in a single column instead (at the expense of the fonts list).

I'd like your opinion on this: should we keep trying to shorten those button titles as much as possible in every translation, or should I just change the layout? Keep in mind that those button names don't have to be exceedingly clear, because they also have tooltips to clear up confusion.

**Comment by JuaniElias** [comment]
Oh I left some double quotation marks that messed up the whole tab. I'll make some corrections now that I can see it in Godot and push the changes.

> I'd like your opinion on this: should we keep trying to shorten those button titles as much as possible in every translation, or should I just change the layout? Keep in mind that those button names don't have to be exceedingly clear, because they also have tooltips to clear up confusion.

It's definitely possible to shorten them, I'll compact them as much as I can since we have the tooltips (I didn't take them into account when translating).
Maybe we should leave comments in the `TRANSLATING.md` file to clarify and warn about those specific cases and keep them below a certain amount of characters. It would be ideal to leave translating tips and comments on the `.csv` files in the `en` folder but that's a bit more complicated from what I've seen and I don't think they'll show up in a cell view program like Excel.
Other than that maybe you should consider redesigning that tab later on but for now it's not that big of a problem in my opinion. The launcher is looking great! Thank you really for making it and releasing it to the public!

**Comment by qrrk** [comment]
Thanks for your feedback! I'll thinks about adding a section for tips.

While you're at it, could you also see if tab names can be shortened, specifically the Soundpacks and Backups tabs? I worry that if any more tabs are added later on, they will not fit and will have to be scrolled. Perhaps just "Sonidos" instead of "Packs de sonido" or something like that...

**Comment by JuaniElias** [comment]
Yeah, I had doubts whether to change "Backups" to "Copias de seguridad" but now that you tell me I'll just leave it like "Backups" since it's also used in Spanish. "Soundpacks" is not that common though, maybe I'll leave the tab name as "Sonido" to keep it short but all the other appearances as "Paquetes de sonido" since just "Sonido" is not that representative of "Soundpacks", just like Sound is not the same as Soundpack.

**Comment by JuaniElias** [comment]
Now it's all finished, it would be great to get a second opinion on the translation but I think it'll work fine as a first attempt.

**Comment by qrrk** [comment]
Just checked it out. Sorry to keep nitpicking, but there are still a couple things I would improve.

1. The Set Font buttons are still a bit too wide. I think we can save a bit more space if we change:
    - "Aplicar al mapa" to "Aplicar al mundo",
    - "Aplicar al mapa general" to just "Aplicar al mapa".

    What do you think?
2. The builds drop-down is no longer wide enough to show the full names of experimental releases.
    
    image

    Maybe shorten "Complicaciones disponsibles" to just "Complicaciones"?

**Comment by JuaniElias** [comment]
It's OK don't worry. 
The thing is that "Overmap" is strange word to translate so I went with the translation used in the Spanish release of Cataclysm which is "Mapa general". I think we should stay consistent on that because those are really specific things in-game.
It just occurred to me that we could just leave a label on top that said "Set to: " and the on the buttons just "Ui", "Map", "Overmap", etc. That would save some space on most translations and it would serve the same purpose. What do you think?
"Compilaciones" (Builds) is a similar situation as Backups, it's a weird word to see in another language. I could leave it as just "Compilaciones" and it'll still serve it's purpose.

**Comment by qrrk** [comment]
> It just occurred to me that we could just leave a label on top that said "Set to: " or "Apply to: " and on the buttons just "UI", "Map", "Overmap", etc. That would save some space on most translations and it would serve the same purpose. What do you think?

It could work, but it would require changes in all other translations that exist so far. I just arranged the buttons in a single column and shrunk a couple other elements a little. Looks okay, I think.

**Pull request merged**
