### PR TITLE
Added EOD & TISH

### PR DESCRIPTION
**Pull request by IT-Techpriest**
Adds Era Of Decay & There Is Still Hope to Catapult
This was mainly written by [AtomicFox556](https://github.com/qrrk/Catapult/issues?q=is%3Apr+is%3Aopen+author%3AAtomicFox556) I just fixed a few bugs from his PR: https://github.com/qrrk/Catapult/pull/109

Also made a exe on my fork, if you don't want to compile yourself

### CODE REVIEW

**Comment by AriaMoradi** [comment]
cc: @AtomicFox556

**Comment by AtomicFox556** [comment]
> * The description string for both EOD and TISH are missing

If I understood this correctly, then I've just needed to add relevant descriptions to "general.csv" files that contain description strings. This was done in #109, this PR doesn't include those changes.

> * The same for the "fetching releases" message

Yup, a fuckup on my part. Should have added respective strings to "release_manager.csv" files for every language.

> * The _*.translation_ files should not be in the repository. The engine generates them locally every time.

Didn't include those in my original PR.

> * If you have DDA stable or BN stable selected and then switch to EOD or TISH, you will get this:
>   ...and you are stuck with the launcher thinking you want the stable branch which does not exist. This case needs to be handled in `apply_game_choice()`.
> 
> Please look into these when you can.

This was handled back in my PR.

**Comment by IT-Techpriest** [comment]
Yeah, most of the issues were because I either didn't know where the relevant file was located or how to use GIt (As I am both new to Git and Godot). Will take a look when I get a chance and update it sometime before the weekend hopefully.

**Comment by AriaMoradi** [comment]
Suppressed by #148

**Pull request closed without merging**
