### PR TITLE
Add EOD and TISH to the launcher

### LINKED ISSUE #93: Add Era Of Decay support to the launcher
Hello, I am the owner of a new fork of DDA named Era Of Decay (a.k.a. EOD) and got a question regarding how to make this fork work with Catapult launcher. Would that be possible?

image

I'm willing to cooperate if there's anything I'd need to do on my part to make that happen.

### LINKED ISSUE #108: Add CDDA - There is still Hope
would be nice if you could add this new fork to the launcher in the future.

https://github.com/Cataclysm-TISH-team/Cataclysm-TISH

### PR DESCRIPTION
**Pull request by AtomicFox556**
Want it done, do it yourself, as usual.

Adding EOD and TISH fork downloads to the launcher.
Fixes #93 
Fixes #108 

Tested the changes by successfully downloading EOD via the launcher and then launching it.

Note: text for Czech, French, Spanish, Turkish, Polish and Chinese were obtained by translating via a Google translator and may be incorrect, as I do not know any of those languages. Pointing out possible mistakes would be appreciated.

### CODE REVIEW

**Comment by IT-Techpriest** [comment]
Hey mate, thanks for the PR! I'm new to using GitHub so I don't know if I can make a PR on a PR, but I fixed a few issues: like the broken "View Experimental Changelog" for EOD & TISH and installing TISH (Since they changed their naming for files). So I hope you're alright with me making a PR myself to help any other impatient people like me that can't wait for Catapult to update!

**Comment by AtomicFox556** [comment]
> Hey mate, thanks for the PR! I'm new to using GitHub so I don't know if I can make a PR on a PR, but I fixed a few issues: like the broken "View Experimental Changelog" for EOD & TISH and installing TISH (Since they changed their naming for files). So I hope you're alright with me making a PR myself to help any other impatient people like me that can't wait for Catapult to update!

Noted, thanks for help.

**Comment by AmarinReyny** [comment]
Is anyone still working on this?

**Comment by AriaMoradi** [comment]
Suppressed by #148

**Pull request closed without merging**
