### PR TITLE
Add MacOS Support

### PR DESCRIPTION
**Pull request by DPS0340**
😄 

If you have any questions or fix, feel free to talk!

### CODE REVIEW

**Comment by qrrk** [comment]
@Osorkonius Please tell me, is it a common practice on modern macOS versions to allow any executables to run, from any source? At least among somewhat experienced users?

You see, DPS0340's code is wildly inconsistent with how Catapult works on other platforms, and I'd rather not have that. I want to try my best to achieve convergent behavior and keep the launcher portable. Are portable apps even a thing on macOS?

Plus, some changes are upcoming in regards to content handling, as well as some infrastructure changes required for those, and that would likely brake the macOS version if it were to be implemented right now.

**Comment by Inglonias** [comment]
the thought occurs to me that there's nothing stopping anyone with access to a Mac from forking this codebase and maintaining a mac version on their own.

**Comment by Daenyth** [comment]
Portable apps really aren't a thing on macos any more. The `Whatever.app/` files are the static files to run the application, and configuration data, state, etc, all gets stored in ~/Library

**Comment by qrrk** [comment]
> Portable apps really aren't a thing on macos any more. The `Whatever.app/` files are the static files to run the application, and configuration data, state, etc, all gets stored in ~/Library

But does this completely rule out apps using custom paths and working without installation?
Because Linux has a somewhat similar system, but it is not enforced, much to the chagrin of our home folders 😆

**Comment by Daenyth** [comment]
It's probably doable, it's just not going to be something that osx users will expect or enjoy

**Comment by qrrk** [comment]
> It's probably doable, it's just not going to be something that osx users will expect or enjoy

Well, that settles it. No sense peeing against the wind. Catapult may get an optional non-portable mode in the future, but I am not sure when or if that will happen. If it happens, we can consider porting again, but the current work will likely be irrelevant in those conditions, so I'm going to close this PR.

**Pull request closed without merging**
