### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by raylemon**
translation to French

### CODE REVIEW

**Comment by qrrk** [comment]
Hi! I'm very happy to see another translation so soon, but this one has a few problems:

- I some places, translated text is longer than what the UI layout can handle, so things start to break. In particular, it's the _Play_ button on the _Game_ tab and the _Set_ buttons on the _Fonts_ tab (see screenshot). Please see if you can make their text shorter.
- BBCode is broken in many places, likely because of some kind of auto-correction in your spreadsheet program: I am noticing that many opening tags use capital letters, e.g. `[U]some text[/u]`.
- Extra spaces before punctuation marks, particularly before colons. That's not the correct punctuation for French, is it?

There may be other issues I didn't notice because I don't read French, so I think a proofreading pass is in order. Let's give this PR the same treatment as for the [Chinese translation](https://github.com/qrrk/Catapult/pull/42):

> Run the project in Godot and play around with it. Check all the tabs, dialogs and tooltips. Make sure all translation pieces show up and that they suit the context in which they are used. Make corrections and commit them, if needed.
> 
> If you can't run the project in Godot, let me know, and I can build it for you (for Windows or Linux).


image

**Comment by raylemon** [comment]
Hi, thanks for the return, and thanks for the job, too ! I have modified some texts. I made some tests, everything seems ok with my resolution.
For the "Play" button on game tab, I didn’t notice the bug. Can you take a screenshot ?

**Comment by qrrk** [comment]
> For the "Play" button on game tab, I didn’t notice the bug. Can you take a screenshot ?

Your text just about fits the width of the button, but it leaves no space for the icon:

image

Also, I am still noticing screwy punctuation in many places:

image

Plus, the font help text still has broken formatting:

image

Finally, the Set Font buttons are still a bit too wide. I suggest the following, even shorter names for them:
- Appl. à UI
- Appl. au monde
- Appl. à la carte
- Appl. à tout

**Comment by raylemon** [comment]
Ok, thanks.
I’ve modified some sentences, I think it’s ok now. If not, let me know !

**Comment by qrrk** [comment]
Looks much better! Some minor corrections may still be needed, but I think I can manage them myself rather than keep nitpicking on your work 😆
Good job. Thank you!

**Comment by qrrk** [comment]
I may have been wrong to blame the font help formatting on you, looks like it was broken by someone earlier, and I didn't notice.

**Pull request merged**
